# Generated by Django 4.2 on 2023-04-03 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('surname', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('cap', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('plan', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('contract', models.CharField(blank=True, max_length=50, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('host_name', models.CharField(blank=True, max_length=50, null=True)),
                ('make', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('memory', models.IntegerField(blank=True, null=True)),
                ('memory_unit', models.CharField(blank=True, choices=[('EB', 'Exabyte'), ('PB', 'Petabyte'), ('TB', 'Terabyte'), ('GB', 'Gigabyte'), ('MB', 'Megabyte'), ('kB', 'Kilobyte'), ('bit', 'Bit')], default='GB', max_length=3, null=True)),
                ('hard_disk', models.IntegerField(blank=True, null=True)),
                ('hard_disk_unit', models.CharField(blank=True, choices=[('EB', 'Exabyte'), ('PB', 'Petabyte'), ('TB', 'Terabyte'), ('GB', 'Gigabyte'), ('MB', 'Megabyte'), ('kB', 'Kilobyte'), ('bit', 'Bit')], default='GB', max_length=3, null=True)),
                ('cpu', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Available'), (1, 'Unavailable')], default=0, null=True)),
                ('history_type', models.IntegerField(blank=True, choices=[(0, 'Storico'), (1, 'Attivo')], default=0, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('test_id', models.IntegerField(blank=True, null=True)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place', to='warehouse_app.place')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deviceuser', to='warehouse_app.deviceuser')),
                ('user_history', models.ManyToManyField(blank=True, null=True, to='warehouse_app.deviceuser')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
