# Generated by Django 4.1.3 on 2022-12-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
        migrations.AddField(
            model_name='device',
            name='Archiviazione',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='Memoria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='cpu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='hard_disk_unit',
            field=models.CharField(blank=True, choices=[('EB', 'Exabyte'), ('PB', 'Petabyte'), ('TB', 'Terabyte'), ('GB', 'Gigabyte'), ('MB', 'Megabyte'), ('kB', 'Kilobyte'), ('bit', 'Bit')], default='GB', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='memory_unit',
            field=models.CharField(blank=True, choices=[('EB', 'Exabyte'), ('PB', 'Petabyte'), ('TB', 'Terabyte'), ('GB', 'Gigabyte'), ('MB', 'Megabyte'), ('kB', 'Kilobyte'), ('bit', 'Bit')], default='GB', max_length=3, null=True),
        ),
    ]
