# Generated by Django 4.1.3 on 2023-02-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='history_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Storico'), (1, 'Attivo')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Available'), (1, 'Unavailable')], default=0, null=True),
        ),
    ]
