# Generated by Django 4.2 on 2023-10-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="phase",
            field=models.IntegerField(
                choices=[
                    (0, "In preparazione"),
                    (1, "Da spedire"),
                    (2, "Spedito"),
                    (3, "Consegnato"),
                ],
                default=0,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Available"), (1, "Unavailable"), (2, "Da eliminare")],
                default=0,
                null=True,
            ),
        ),
    ]
