# Generated by Django 4.2 on 2023-06-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_app", "0002_remove_device_test_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="note",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
