# Generated by Django 4.1.3 on 2023-03-02 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0002_device_history_type_alter_device_serial_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='test_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deviceuser', to='warehouse_app.deviceuser'),
        ),
    ]
