# Generated by Django 4.1.3 on 2022-11-15 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0003_place_device_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='street',
            new_name='address',
        ),
    ]
