# Generated by Django 4.2 on 2023-06-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse_app", "0003_alter_device_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="addr_ip",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
