# Generated by Django 4.1.3 on 2022-12-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0004_device_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Historic', 'Historic')], default='Active', max_length=20, null=True),
        ),
    ]
