# Generated by Django 4.1.3 on 2022-11-17 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0005_device_user_alter_device_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place', to='warehouse_app.place'),
        ),
    ]
