# Generated by Django 4.1.3 on 2022-12-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0005_alter_device_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Active'), (1, 'Historic')], default=0, null=True),
        ),
    ]
