# Generated by Django 4.1.3 on 2022-12-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0006_alter_device_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='user_history',
            field=models.ManyToManyField(blank=True, null=True, to='warehouse_app.deviceuser'),
        ),
    ]
