# Generated by Django 4.1.3 on 2022-12-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0007_alter_device_user_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='status_bol',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
