# Generated by Django 4.1.3 on 2022-12-30 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0010_alter_device_status_bol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='status_bol',
        ),
    ]
