# Generated by Django 4.1.3 on 2022-12-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_app', '0011_remove_device_status_bol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Active'), (1, 'Historic'), (2, 'Available')], default=0, null=True),
        ),
    ]
